### PR TITLE
Use goToNumber directly with mention links in the same discussion

### PR DESCRIPTION
**Pull request by askvortsov1**
Update mentions to account for https://github.com/flarum/core/pull/2377.

### CODE REVIEW

**Comment by SychO9** [comment]
It works if you click directly on the mention, but not when you click on the dropdown item :thinking:

also the links in the reply previews dropdown would also need similar logic with this change

**Comment by askvortsov1** [comment]
> also the links in the reply previews dropdown would also need similar logic with this change

Good catch! Although this problem is actually present in b13 too, so it wasn't introduced here.



> It works if you click directly on the mention, but not when you click on the dropdown item

Do you mean the autocomplete dropdown? From testing on Discuss, I'm not sure it's supposed to scroll you there.

**Comment by SychO9** [comment]
> Good catch! Although this problem is actually present in b13 too, so it wasn't introduced here.

I meant the `Post-mentionedBy-preview` dropdown items (present in **addMentionedByList.js**)

> Do you mean the autocomplete dropdown? From testing on Discuss, I'm not sure it's supposed to scroll you there.

No, similar to the above I meant the `PostMention-preview` dropdown items (present in **addPostMentionPreviews.js**)

Both dropdowns, are supposed to scroll to the related post when clicking on an item, here a pic will be more helpful to communicate what I mean:

Screenshot from 2020-10-08 19-33-36
Screenshot from 2020-10-08 19-34-20

**Comment by askvortsov1** [comment]
Ahhhhh ok I understand, thanks! Forgot those existed lol (awkward!)

**Comment by askvortsov1** [comment]
This will (hopefully) no longer be necessary.

**Pull request closed without merging**
